'use client';
import {useEffect,useMemo,useState} from 'react';
type Accuracy={testedDraws:number;picksPerDraw:number;straightHits:number;boxHits:number;straightRate:number;boxRate:number;digitMatchRate:number};
type Prediction={number:string;score:number;relativeScore:number;reasons:string[]};
type Mode='hybrid'|'ai'|'statistical'|'random'; type View='predictions'|'results';
type LiveRow={id?:string;target_round:number;model:Mode;model_version:string;picks:string[];status:'pending'|'settled';winning_number?:string|null;straight_hit?:boolean|null;box_hit?:boolean|null;best_digit_match?:number|null;created_at?:string};
type ModelSummary={model:Mode;modelVersion:string;draws:number;straightHits:number;boxHits:number;straightRate:number;boxRate:number;avgDigitMatch:number;stakeYen:number;returnYen:number|null;roiPercent:number|null};
type Bench={model:Exclude<Mode,'random'>;modelVersion:string;pairedDraws:number;avgDigitMatch:number;randomAvgDigitMatch:number;digitLift:number;straightDelta:number;boxDelta:number};
type Data={game:string;latest:{round:number;date:string;number:string;source?:string};sourceInfo?:{primary:string;historySize:number;latestSource?:string};targetRound:number;targetDate:string|null;predictions:Record<Mode,Prediction[]>;accuracy:Record<Mode,Accuracy>;benchmark:{statisticalLift:number;aiLift:number;hybridLift:number;note:string};modelVersions:Record<Mode,string>;aiInfo:{model:string;trainingRows:number;features:string};live:{enabled:boolean;summary:{startedAt:string|null;totalSettled:number;byModel:ModelSummary[];byVersion:ModelSummary[];benchmark:Bench[]};history:LiveRow[]};updatedAt:string;notice:string};
const labels:Record<Mode,string>={hybrid:'HYBRID',ai:'AI',statistical:'STATISTICAL',random:'RANDOM'};
const modes:Mode[]=['hybrid','ai','statistical','random'];
export default function Home(){
 const[game,setGame]=useState('numbers4');const[mode,setMode]=useState<Mode>('hybrid');const[view,setView]=useState<View>('predictions');const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{setLoading(true);setError('');fetch(`/api/data?game=${game}`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'取得失敗');return b}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[game]);
 const accuracy=data?.accuracy[mode];
 const grouped=useMemo(()=>{const map=new Map<number,LiveRow[]>();for(const row of data?.live.history??[]){const arr=map.get(row.target_round)??[];arr.push(row);map.set(row.target_round,arr)}return [...map.entries()].sort((a,b)=>b[0]-a[0])},[data]);
 const lift=(m:Mode)=>m==='random'?0:m==='hybrid'?(data?.benchmark.hybridLift??0):m==='ai'?(data?.benchmark.aiLift??0):(data?.benchmark.statisticalLift??0);
 return <main><header><div className="eyebrow">PUBLIC FORECAST VERIFICATION PLATFORM / V7</div><h1>NUMBERS <span>ORACLE</span></h1><p>AIは本当にランダムより強いのか。予想を事前保存し、同条件で検証する。</p></header>
 <nav className="main-nav"><button className={game==='numbers3'?'on':''} onClick={()=>setGame('numbers3')}>NUMBERS 3</button><button className={game==='numbers4'?'on':''} onClick={()=>setGame('numbers4')}>NUMBERS 4</button><button className={view==='predictions'?'sub-on':''} onClick={()=>setView('predictions')}>予想・比較</button><button className={view==='results'?'sub-on':''} onClick={()=>setView('results')}>公開実績</button></nav>
 {loading?<section className="loading">LOADING CACHED FORECAST...</section>:error?<section className="error">{error}</section>:data&&<>
 <section className="status"><div><small>DATA LINK</small><b className="ok">{data.sourceInfo?.latestSource==='public-fallback'?'PUBLIC VERIFIED':'BANK VERIFIED'}</b></div><div><small>LATEST DRAW</small><b>第{data.latest.round}回 / {data.latest.number}</b></div><div><small>NEXT TARGET</small><b className="accent">第{data.targetRound}回</b><small>{data.targetDate??'日程確認中'}</small></div><div><small>LIVE STORAGE</small><b className="ok">CONNECTED</b></div></section>
 {view==='predictions'?<>
 <section><h2>MODEL SELECT — SAME 10 PICKS</h2><div className="mode-tabs">{modes.map(m=><button key={m} className={mode===m?'on':''} onClick={()=>setMode(m)}>{labels[m]} 10</button>)}</div><p className="accuracy-note">MODEL VERSION: {data.modelVersions[mode]}。RANDOMは対象回だけを種にした再現可能な基準モデルで、履歴を一切使いません。</p></section>
 <section><div className="section-head"><h2>4-MODEL BACKTEST BENCHMARK</h2><span>同じ対象回・各10口</span></div><div className="benchmark-table"><div className="bhead">MODEL</div><div className="bhead">STRAIGHT</div><div className="bhead">BOX</div><div className="bhead">DIGIT MATCH</div><div className="bhead">vs RANDOM</div>{modes.map(m=><div className="brow" key={m}><b>{labels[m]}</b><span>{data.accuracy[m].straightHits}/{data.accuracy[m].testedDraws}</span><span>{data.accuracy[m].boxHits}/{data.accuracy[m].testedDraws}</span><span>{data.accuracy[m].digitMatchRate.toFixed(1)}%</span><span className={lift(m)>0?'ok':lift(m)<0?'accent':''}>{m==='random'?'BASELINE':`${lift(m)>0?'+':''}${lift(m).toFixed(1)}pt`}</span></div>)}</div><p className="accuracy-note">{data.benchmark.note}</p></section>
 {accuracy&&<section><h2>{labels[mode]} BACKTEST DETAIL</h2><div className="accuracy"><div><small>STRAIGHT</small><strong>{accuracy.straightRate.toFixed(2)}%</strong><p>{accuracy.straightHits}/{accuracy.testedDraws}回</p></div><div><small>BOX MATCH</small><strong>{accuracy.boxRate.toFixed(2)}%</strong><p>{accuracy.boxHits}/{accuracy.testedDraws}回</p></div><div><small>DIGIT MATCH</small><strong>{accuracy.digitMatchRate.toFixed(1)}%</strong><p>最良候補の桁一致率</p></div><div><small>VERSION</small><strong className="version">{data.modelVersions[mode]}</strong><p>成績を混在させません</p></div></div></section>}
 <section><div className="section-head"><h2>NEXT {labels[mode]} PREDICTIONS</h2><span>第{data.targetRound}回候補</span></div><div className="grid">{data.predictions[mode].map((p,i)=><article key={p.number}><div className="rank">RANK {String(i+1).padStart(2,'0')}</div><div className="number">{p.number}</div><div className="meter"><i style={{width:`${p.score}%`}}/></div><div className="metrics"><strong>SCORE {p.score}</strong><strong>RELATIVE {p.relativeScore}</strong></div><p>{p.reasons.join(' / ')}</p></article>)}</div></section></>:
 <><section><div className="section-head"><h2>LIVE PERFORMANCE — PRECOMMITTED ONLY</h2><span>抽せん前に保存された予想のみ</span></div><div className="accuracy live four">{data.live.summary.byModel.map(s=><div key={s.model}><small>{labels[s.model]} / {s.modelVersion}</small><strong>{s.straightHits} / {s.draws}</strong><p>BOX {s.boxHits}回・平均{s.avgDigitMatch}桁一致</p><p>投資 ¥{s.stakeYen.toLocaleString()} / 回収 {s.returnYen===null?'集計待ち':`¥${s.returnYen.toLocaleString()}`} / ROI {s.roiPercent===null?'—':`${s.roiPercent}%`}</p></div>)}</div></section>
 <section><h2>LIVE HEAD-TO-HEAD vs RANDOM</h2>{data.live.summary.benchmark.every(b=>b.pairedDraws===0)?<div className="empty">RANDOMを含むV7予想が抽せん後に確定すると、同じ回だけを使った比較が始まります。</div>:<div className="h2h">{data.live.summary.benchmark.map(b=><div key={b.model}><b>{labels[b.model]}</b><span>{b.pairedDraws} paired draws</span><strong className={b.digitLift>0?'ok':b.digitLift<0?'accent':''}>{b.digitLift>0?'+':''}{b.digitLift} 桁</strong><small>平均桁一致 {b.avgDigitMatch} vs RANDOM {b.randomAvgDigitMatch} / STR Δ {b.straightDelta} / BOX Δ {b.boxDelta}</small></div>)}</div>}</section>
 <section><h2>MODEL VERSION HISTORY</h2><div className="version-list">{data.live.summary.byVersion.map(v=><div key={`${v.model}-${v.modelVersion}`}><b>{labels[v.model]}</b><span>{v.modelVersion}</span><small>{v.draws} settled / STR {v.straightHits} / BOX {v.boxHits}</small></div>)}</div></section>
 <section><h2>FORECAST LEDGER</h2>{grouped.length===0?<div className="empty">保存済み予想はまだありません。</div>:<div className="ledger">{grouped.slice(0,30).map(([round,rows])=><div className="ledger-row four" key={round}><div className="round">第{round}回<br/><small>{rows[0]?.status==='settled'?`当選 ${rows[0]?.winning_number}`:'判定待ち'}</small></div>{rows.map(r=><div className="model-result" key={`${r.model}-${r.model_version}`}><b>{labels[r.model]}<br/>{r.model_version}</b><span>{r.status==='pending'?'PENDING':r.straight_hit?'STRAIGHT':r.box_hit?'BOX':`${r.best_digit_match??0}桁一致`}</span><small>{r.picks.slice(0,3).join(' / ')} ...</small></div>)}</div>)}</div>}</section></>}
 <footer><p>{data.notice}</p><p>最終解析：{new Date(data.updatedAt).toLocaleString('ja-JP')}</p></footer></>}
 </main>}
