'use client';
import {useEffect,useMemo,useState} from 'react';
type Accuracy={testedDraws:number;picksPerDraw:number;straightHits:number;boxHits:number;straightRate:number;boxRate:number};
type Prediction={number:string;score:number;relativeScore:number;reasons:string[]};
type Mode='hybrid'|'ai'|'statistical'; type View='predictions'|'results';
type LiveRow={id?:number;target_round:number;model:Mode;picks:string[];status:'pending'|'settled';winning_number?:string|null;straight_hit?:boolean|null;box_hit?:boolean|null;best_digit_match?:number|null;created_at?:string};
type ModelSummary={model:Mode;draws:number;straightHits:number;boxHits:number;straightRate:number;boxRate:number;avgDigitMatch:number;stakeYen:number;returnYen:number|null;roiPercent:number|null};
type Data={game:string;latest:{round:number;date:string;number:string;source?:string};sourceInfo?:{primary:string;historySize:number;latestSource?:string};targetRound:number;targetDate:string|null;predictions:Record<Mode,Prediction[]>;accuracy:{statistical:Accuracy;ai:Accuracy;hybrid:Accuracy};aiInfo:{model:string;trainingRows:number;features:string};live:{enabled:boolean;summary:{startedAt:string|null;totalSettled:number;byModel:ModelSummary[]};history:LiveRow[]};updatedAt:string;notice:string};
const labels:Record<Mode,string>={hybrid:'HYBRID',ai:'AI',statistical:'STATISTICAL'};
export default function Home(){
 const[game,setGame]=useState('numbers4');const[mode,setMode]=useState<Mode>('hybrid');const[view,setView]=useState<View>('predictions');const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{setLoading(true);setError('');fetch(`/api/data?game=${game}`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'取得失敗');return b}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[game]);
 const accuracy=mode==='statistical'?data?.accuracy.statistical:mode==='ai'?data?.accuracy.ai:data?.accuracy.hybrid;
 const grouped=useMemo(()=>{const map=new Map<number,LiveRow[]>();for(const row of data?.live.history??[]){const arr=map.get(row.target_round)??[];arr.push(row);map.set(row.target_round,arr)}return [...map.entries()].sort((a,b)=>b[0]-a[0])},[data]);
 return <main><header><div className="eyebrow">PUBLIC FORECAST VERIFICATION PLATFORM / V6.4</div><h1>NUMBERS <span>ORACLE</span></h1><p>公式履歴で予想し、公開後の予想を保存・自動照合して実績を開示</p></header>
 <nav className="main-nav"><button className={game==='numbers3'?'on':''} onClick={()=>setGame('numbers3')}>NUMBERS 3</button><button className={game==='numbers4'?'on':''} onClick={()=>setGame('numbers4')}>NUMBERS 4</button><button className={view==='predictions'?'sub-on':''} onClick={()=>setView('predictions')}>予想</button><button className={view==='results'?'sub-on':''} onClick={()=>setView('results')}>公開実績</button></nav>
 {loading?<section className="loading">LOADING CACHED FORECAST...</section>:error?<section className="error">{error}</section>:data&&<>
 <section className="status"><div><small>DATA LINK</small><b className="ok">{data.sourceInfo?.latestSource==='public-fallback'?'PUBLIC VERIFIED':'BANK VERIFIED'}</b></div><div><small>LATEST DRAW</small><b>第{data.latest.round}回 / {data.latest.number}</b></div><div><small>NEXT TARGET</small><b className="accent">第{data.targetRound}回</b><small>{data.targetDate??'日程確認中'}</small></div><div><small>LIVE STORAGE</small><b className={data.live.enabled?'ok':'warn'}>{data.live.enabled?'CONNECTED':'NOT SET'}</b></div></section>
 {view==='predictions'?<>
 <section><h2>MODEL SELECT</h2><div className="mode-tabs">{(['hybrid','ai','statistical'] as Mode[]).map(m=><button key={m} className={mode===m?'on':''} onClick={()=>setMode(m)}>{labels[m]} 10</button>)}</div><p className="accuracy-note">AI特徴量：{data.aiInfo.features}。スコアは当せん確率ではなく候補内順位です。</p></section>
 {accuracy&&<section><h2>{labels[mode]} BACKTEST — 過去検証</h2><div className="accuracy"><div><small>STRAIGHT</small><strong>{accuracy.straightRate.toFixed(2)}%</strong><p>{accuracy.straightHits}/{accuracy.testedDraws}回</p></div><div><small>BOX</small><strong>{accuracy.boxRate.toFixed(2)}%</strong><p>{accuracy.boxHits}/{accuracy.testedDraws}回</p></div><div><small>PICKS</small><strong>{accuracy.picksPerDraw}</strong><p>1回の候補数</p></div><div><small>TYPE</small><strong className="warn">BACKTEST</strong><p>公開後実績ではありません</p></div></div></section>}
 <section><div className="section-head"><h2>NEXT {labels[mode]} PREDICTIONS</h2><span>第{data.targetRound}回候補</span></div><div className="grid">{data.predictions[mode].map((p,i)=><article key={p.number}><div className="rank">RANK {String(i+1).padStart(2,'0')}</div><div className="number">{p.number}</div><div className="meter"><i style={{width:`${p.score}%`}}/></div><div className="metrics"><strong>SCORE {p.score}</strong><strong>RELATIVE {p.relativeScore}</strong></div><p>{p.reasons.join(' / ')}</p></article>)}</div></section></>:
 <><section><div className="section-head"><h2>LIVE PERFORMANCE — 公開後実績</h2><span>予想保存後の実績のみ</span></div>{!data.live.enabled?<div className="setup"><b>Supabase未接続</b><p>環境変数を設定すると、Cronが予想を保存し抽せん後に自動照合します。ZIP内のsupabase.sqlを実行してください。</p></div>:<div className="accuracy live">{data.live.summary.byModel.map(s=><div key={s.model}><small>{labels[s.model]}</small><strong>{s.straightHits} / {s.draws}</strong><p>BOX {s.boxHits}回・平均{s.avgDigitMatch}桁一致</p><p>投資 ¥{s.stakeYen.toLocaleString()} / 回収 {s.returnYen===null?'集計待ち':`¥${s.returnYen.toLocaleString()}`} / ROI {s.roiPercent===null?'—':`${s.roiPercent}%`}</p></div>)}</div>}</section>
 <section><h2>FORECAST LEDGER</h2>{grouped.length===0?<div className="empty">保存済み予想はまだありません。Cron実行後から記録されます。</div>:<div className="ledger">{grouped.map(([round,rows])=><div className="ledger-row" key={round}><div className="round">第{round}回<br/><small>{rows[0]?.status==='settled'?`当選 ${rows[0]?.winning_number}`:'判定待ち'}</small></div>{rows.map(r=><div className="model-result" key={r.model}><b>{labels[r.model]}</b><span>{r.status==='pending'?'PENDING':r.straight_hit?'STRAIGHT':r.box_hit?'BOX':`${r.best_digit_match??0}桁一致`}</span><small>{r.picks.slice(0,3).join(' / ')} ...</small></div>)}</div>)}</div>}</section></>}
 <footer><p>{data.notice}</p><p>最終解析：{new Date(data.updatedAt).toLocaleString('ja-JP')}</p></footer></>}
 </main>}
