import type { Draw, Game, Prediction } from './types';
export type ModelMode='hybrid'|'ai'|'statistical';
export type SavedForecast={id?:number;game:Game;target_round:number;target_date:string|null;model:ModelMode;picks:string[];scores:number[];purchase_type?:'straight';stake_yen?:number;return_yen?:number|null;roi_percent?:number|null;created_at?:string;settled_at?:string|null;winning_number?:string|null;straight_hit?:boolean|null;box_hit?:boolean|null;best_digit_match?:number|null;status?:'pending'|'settled'};
function cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'')??'';const key=process.env.SUPABASE_SERVICE_ROLE_KEY??'';return{enabled:Boolean(url&&key),url,key}}
export function persistenceEnabled(){return cfg().enabled}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const c=cfg();if(!c.enabled)throw new Error('Supabase persistence is not configured');const h=new Headers(init.headers);h.set('apikey',c.key);h.set('Authorization',`Bearer ${c.key}`);h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:h,cache:'no-store'});if(!r.ok)throw new Error(`Supabase ${r.status}: ${await r.text()}`);const t=await r.text();return (t?JSON.parse(t):null) as T}
export async function saveForecast(game:Game,targetRound:number,targetDate:string|null,model:ModelMode,predictions:Prediction[]){if(!persistenceEnabled())return null;const stake=predictions.length*200;const payload={game,target_round:targetRound,target_date:targetDate,model,picks:predictions.map(p=>p.number),scores:predictions.map(p=>p.score),purchase_type:'straight',stake_yen:stake,status:'pending'};const rows=await request<SavedForecast[]>('forecasts?on_conflict=game,target_round,model',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});return rows?.[0]??null}
const boxKey=(v:string)=>[...v].sort().join('');
export function settleValues(picks:string[],winning:string){const straight=picks.includes(winning);const box=picks.some(v=>boxKey(v)===boxKey(winning));const best=picks.reduce((m,v)=>Math.max(m,[...v].filter((c,i)=>c===winning[i]).length),0);return{straight_hit:straight,box_hit:box,best_digit_match:best}}
export async function settleForecasts(draws:Draw[]){if(!persistenceEnabled())return{settled:0};const game=draws[0]?.game;if(!game)return{settled:0};const pending=await request<SavedForecast[]>(`forecasts?game=eq.${game}&status=eq.pending&select=*`);const byRound=new Map(draws.map(d=>[d.round,d]));let settled=0;for(const row of pending){const draw=byRound.get(row.target_round);if(!draw||!row.id)continue;const result=settleValues(row.picks,draw.number);const payout=result.straight_hit?(draw.payouts?.straight??null):0;const stake=row.stake_yen??row.picks.length*200;const roi=payout===null?null:Number((((payout-stake)/stake)*100).toFixed(2));await request(`forecasts?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({...result,winning_number:draw.number,return_yen:payout,roi_percent:roi,status:'settled',settled_at:new Date().toISOString()})});settled++}return{settled}}
export async function getForecasts(game:Game,limit=120){if(!persistenceEnabled())return[] as SavedForecast[];return request<SavedForecast[]>(`forecasts?game=eq.${game}&select=*&order=target_round.desc,model.asc&limit=${limit}`)}
export function summarizeLive(rows:SavedForecast[]){const settled=rows.filter(r=>r.status==='settled');const byModel=(['hybrid','ai','statistical'] as ModelMode[]).map(model=>{const items=settled.filter(r=>r.model===model),n=items.length,stake=items.reduce((s,r)=>s+(r.stake_yen??0),0),ret=items.reduce((s,r)=>s+(r.return_yen??0),0),known=items.some(r=>r.return_yen!==null&&r.return_yen!==undefined);return{model,draws:n,straightHits:items.filter(r=>r.straight_hit).length,boxHits:items.filter(r=>r.box_hit).length,straightRate:n?Number((items.filter(r=>r.straight_hit).length/n*100).toFixed(2)):0,boxRate:n?Number((items.filter(r=>r.box_hit).length/n*100).toFixed(2)):0,avgDigitMatch:n?Number((items.reduce((s,r)=>s+(r.best_digit_match??0),0)/n).toFixed(2)):0,stakeYen:stake,returnYen:known?ret:null,roiPercent:known&&stake?Number((((ret-stake)/stake)*100).toFixed(2)):null}});return{startedAt:rows.length?[...rows].sort((a,b)=>(a.created_at??'').localeCompare(b.created_at??''))[0].created_at:null,totalSettled:settled.length,byModel}}
