create table if not exists public.forecasts (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('numbers3','numbers4')),
  target_round integer not null,
  target_date date,
  model text not null check (model in ('hybrid','ai','statistical')),
  picks jsonb not null,
  scores jsonb not null,
  purchase_type text not null default 'straight' check (purchase_type in ('straight')),
  stake_yen integer not null default 0,
  return_yen integer,
  roi_percent numeric,
  status text not null default 'pending' check (status in ('pending','settled')),
  winning_number text,
  straight_hit boolean,
  box_hit boolean,
  best_digit_match integer,
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  unique(game,target_round,model)
);
alter table public.forecasts add column if not exists purchase_type text not null default 'straight';
alter table public.forecasts add column if not exists stake_yen integer not null default 0;
alter table public.forecasts add column if not exists return_yen integer;
alter table public.forecasts add column if not exists roi_percent numeric;
alter table public.forecasts alter column target_date type date using nullif(target_date::text,'')::date;
alter table public.forecasts enable row level security;
create index if not exists forecasts_game_round_idx on public.forecasts(game,target_round desc);
create index if not exists forecasts_status_idx on public.forecasts(status);
